apiVersion: v1
kind: Secret
metadata:
  name: db-connstring
  labels: {{ .Values.labels | toYaml | nindent 4 }}
type: Opaque
stringData:
  db-connstring: {{ .Values.database.url | default "postgres://user:password@hostname/dbname" | quote }}
