{{ if .Values.ingress.domain }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  labels: {{ .Values.labels | toYaml | nindent 4 }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.ingress.domain }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecommerce-demo-api
                port:
                  number: 80
{{ end }}
