apiVersion: v1
kind: Service
metadata:
  name: ecommerce-demo-api
  labels: {{ .Values.labels | toYaml | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: ecommerce-demo-api
