name: Cleanup Neon Branch from PR
on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    steps:
    - name: Delete Neon PR Branch
      uses: neondatabase/delete-branch-action@v2
      with:
        project_id: ${{ secrets.NEON_PROJECT_ID }}
        api_key: ${{ secrets.NEON_API_KEY }}
        branch: pr-${{ github.event.number }}
